[package]
name = "server"
version = "0.1.0"
authors = ["Øystein Hiåsen <oystein.hiaasen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland-server = "0.26.6"
calloop = "0.6.2"